name: Build LaTeX document
on: [push, pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      # - name: Compile Example LaTeX document
      #   uses: xu-cheng/latex-action@v3
      #   # continue-on-error: true
      #   with:
      #     root_file: example.tex
      #     latexmk_use_lualatex: true
      #     latexmk_shell_escape: true
      #     pre_compile: |
      #       apk add msttcorefonts-installer fontconfig
      #       update-ms-fonts
      #       fc-cache -f
      - name: Compile Main LaTeX document
        uses: xu-cheng/latex-action@v3
        # continue-on-error: true
        with:
          root_file: main-scnu.tex
          latexmk_use_lualatex: true
          pre_compile: |
            apk add msttcorefonts-installer fontconfig
            update-ms-fonts
            fc-cache -f
